export const GLOSSARY: [string, string, string][] = [
  ['Thread', 'A single line of work. It does one thing at a time, in order.', '#e3e3e3'],
  ['JS thread', 'Where your React code, hooks and handlers run.', '#b39dff'],
  ['UI thread', 'The app’s main thread. Draws the screen and receives touches.', '#f291c4'],
  ['Shadow thread', 'In the old architecture, the thread that ran layout on its own copy of the tree.', '#79d49c'],
  ['Bridge', 'The old connection between JS and native. Carries batched, asynchronous JSON messages.', '#f2b35b'],
  ['Serialize', 'Turn an object into text, like JSON, so it can be sent. Parsing turns it back.', '#f2b35b'],
  ['Batch', 'A group of messages sent together.', '#f2b35b'],
  ['Asynchronous', 'You send a request and carry on; the answer arrives later.', '#e3e3e3'],
  ['Frame', 'One picture on screen. At 60 per second, each gets 16.6 ms.', '#e3e3e3'],
  ['Dropped frame', 'A frame that wasn’t ready in time. The user sees a stutter.', '#f0694f'],
  ['Native module', 'Platform code (Swift, Kotlin, Java, Objective-C) that JS can call.', '#9fb0c3'],
  ['C++', 'A fast, lower-level language that runs on iOS and Android. The New Architecture’s shared core.', '#58c4dc'],
  ['JSI', 'JavaScript Interface. Lets JS hold references to C++ objects and call them directly.', '#58c4dc'],
  ['Host object', 'A C++ object JS can use like a normal object.', '#58c4dc'],
  ['Turbo Module', 'A native module built on JSI that loads the first time it’s used.', '#58c4dc'],
  ['Codegen', 'A build-time tool that turns a TypeScript spec into typed native code.', '#58c4dc'],
  ['Fabric', 'The New Architecture’s renderer.', '#58c4dc'],
  ['Yoga', 'The layout engine that turns flexbox styles into positions and sizes.', '#79d49c'],
  ['Shadow tree', 'A C++ copy of your UI with layout information.', '#58c4dc'],
  ['Render · Commit · Mount', 'Fabric’s phases: build the tree, compute layout and seal it, apply changes to views.', '#58c4dc'],
  ['Host view', 'A real platform view, like UIView on iOS or View on Android.', '#f291c4'],
  ['Interop layer', 'Lets old-style modules and components run in the New Architecture.', '#58c4dc'],
]
