import { C } from '../sim/colors'
export const GLOSSARY: [string, string, string][] = [
  ['Thread', 'A single line of work. It does one thing at a time, in order.', C.text],
  ['JS thread', 'Where your React code, hooks and handlers run.', C.js],
  ['UI thread', 'The app’s main thread. Draws the screen and receives touches.', C.ui],
  ['Shadow thread', 'In the old architecture, the thread that ran layout on its own copy of the tree.', C.shadow],
  ['Bridge', 'The old connection between JS and native. Carries batched, asynchronous JSON messages.', C.old],
  ['Serialize', 'Turn an object into text, like JSON, so it can be sent. Parsing turns it back.', C.old],
  ['Batch', 'A group of messages sent together.', C.old],
  ['Asynchronous', 'You send a request and carry on; the answer arrives later.', C.text],
  ['Frame', 'One picture on screen. At 60 per second, each gets 16.6 ms.', C.text],
  ['Dropped frame', 'A frame that wasn’t ready in time. The user sees a stutter.', C.load],
  ['Native module', 'Platform code (Swift, Kotlin, Java, Objective-C) that JS can call.', C.native],
  ['C++', 'A fast, lower-level language that runs on iOS and Android. The New Architecture’s shared core.', C.new],
  ['JSI', 'JavaScript Interface. Lets JS hold references to C++ objects and call them directly.', C.new],
  ['Host object', 'A C++ object JS can use like a normal object.', C.new],
  ['Turbo Module', 'A native module built on JSI that loads the first time it’s used.', C.new],
  ['Codegen', 'A build-time tool that turns a TypeScript or Flow spec into typed native interfaces.', C.new],
  ['Fabric', 'The New Architecture’s renderer.', C.new],
  ['Yoga', 'The layout engine that turns flexbox styles into positions and sizes.', C.shadow],
  ['Shadow tree', 'A C++ copy of your UI with layout information.', C.new],
  ['Render · Commit · Mount', 'Fabric’s phases: build the tree, compute layout and seal it, apply changes to views.', C.new],
  ['Concurrent rendering', 'React can pause a render, let urgent work go first, and throw unfinished work away. Needs the New Architecture.', C.new],
  ['Urgent update', 'An update the user expects to see right away, like a tab highlight. React renders it before any transition.', C.js],
  ['Transition', 'An update marked with startTransition as able to wait. React renders it in slices it can interrupt.', C.new],
  ['Host view', 'A real platform view, like UIView on iOS or View on Android.', C.ui],
  ['Interop layer', 'Lets old-style modules and components run in the New Architecture.', C.new],
]
