import type { Preset, PresetId } from './types'

/** Preset definitions, verbatim from Playground.dc.html `static PRESETS`. */
export const PRESETS: readonly Preset[] = [
  {
    id: 'tap',
    name: 'Button tap → native module',
    file: 'Counter.tsx',
    p: { style: 'medium', step: 1 },
    mods: ['Haptics', 'Storage', 'Camera'],
    desc: 'A press that vibrates and updates a counter. Follow it from the screen into JS, out to a native module, and back to the screen.',
    tree: [
      [0, 'Counter'],
      [1, 'Pressable', 'View', 12],
      [2, 'Text', 'Text', 14],
    ],
    code: [
      'function Counter() {',
      '  const [count, setCount] = useState(0);',
      '  const onPress = () => {',
      "    Haptics.impact('§style§');",
      '    setCount(c => c + §step§);',
      '  };',
      '  return <Pressable onPress={onPress}><Text>{count}</Text></Pressable>;',
      '}',
    ],
  },
  {
    id: 'startup',
    name: 'App startup',
    file: 'index.tsx',
    p: { modules: 12 },
    mods: null,
    desc: 'From launch to first screen. Change how many native modules the app links and watch who pays for them.',
    tree: [
      [0, 'App'],
      [1, 'Home'],
      [2, 'Header', 'View', 2],
      [2, 'List', 'ScrollView', 3],
      [3, 'Row ×4', 'View', 4],
    ],
    code: [
      '// native modules linked into this app',
      'const LINKED_MODULES = §modules§;',
      '',
      "AppRegistry.registerComponent('App', () => App);",
      'function App() {',
      "  const theme = Storage.getString('theme');",
      "  Analytics.track('open');",
      '  return <Home theme={theme} />;',
      '}',
    ],
  },
  {
    id: 'scroll',
    name: 'onScroll with setState',
    file: 'Feed.tsx',
    p: { work: 6 },
    mods: [],
    rate: true,
    desc: 'A header that shows the scroll position, updated from JS on every scroll event. Raise the event rate or the handler’s work.',
    tree: [
      [0, 'Feed'],
      [1, 'ScrollView', 'ScrollView', 7],
      [2, 'Header', 'Text', 31],
      [2, 'Row ×20', 'View', 40],
    ],
    code: [
      'function Feed() {',
      '  const [y, setY] = useState(0);',
      '  const onScroll = (e) => {',
      '    setY(e.nativeEvent.contentOffset.y);',
      '    formatHeader(y); // ~§work§ ms of JS',
      '  };',
      '  return <ScrollView onScroll={onScroll} scrollEventThrottle={16} />;',
      '}',
    ],
  },
  {
    id: 'anim',
    name: 'Animation: native driver',
    file: 'Card.tsx',
    p: { duration: 300, native: 'false', busy: 120 },
    mods: [],
    desc: 'A slide-in animation while JS is busy parsing data. Flip useNativeDriver between false and true.',
    tree: [
      [0, 'Card'],
      [1, 'Animated.View', 'View', 7],
    ],
    code: [
      'const x = useRef(new Animated.Value(0)).current;',
      'Animated.timing(x, {',
      '  toValue: 1,',
      '  duration: §duration§,',
      '  useNativeDriver: §native§,',
      '}).start();',
      '// meanwhile, JS parses a big response',
      'JSON.parse(feedText); // ~§busy§ ms',
    ],
  },
  {
    id: 'measure',
    name: 'Measuring layout',
    file: 'Tooltip.tsx',
    p: { gap: 8 },
    mods: [],
    desc: 'A tooltip that positions itself under a button by measuring it. Watch where it appears first.',
    tree: [
      [0, 'Screen'],
      [1, 'Button', 'View', 12],
      [1, 'Tooltip'],
      [2, 'View', 'View', 40],
      [3, 'Text', 'Text', 41],
    ],
    code: [
      'function Tooltip({ anchor }) {',
      '  const [top, setTop] = useState(0);',
      '  useLayoutEffect(() => {',
      '    anchor.current.measure((x, y, w, h) =>',
      '      setTop(y + h + §gap§));',
      '  }, []);',
      '  return <View style={{ top }}><Text>Saved</Text></View>;',
      '}',
    ],
  },
  {
    id: 'heavy',
    name: 'Heavy JS loop freezes taps',
    file: 'Report.tsx',
    p: { iterations: 50000000 },
    mods: [],
    rate: true,
    desc: 'A big loop runs on the JS thread while the user keeps tapping. Event rate sets how fast they tap.',
    tree: [
      [0, 'Report'],
      [1, 'Button', 'View', 3],
      [1, 'Button', 'View', 5],
      [1, 'Text', 'Text', 8],
    ],
    code: [
      'function Report() {',
      '  const onBuild = () => {',
      '    let sum = 0;',
      '    for (let i = 0; i < §iterations§; i++) sum += i;',
      '    setReport(sum);',
      '  };',
      '  const onTap = () => setTaps(t => t + 1);',
      '}',
    ],
  },
  {
    id: 'payload',
    name: 'Large payload to native',
    file: 'Sync.tsx',
    p: { rows: 2000 },
    mods: ['Db'],
    desc: 'Saving a few thousand rows through a native database module. Change the row count.',
    tree: [
      [0, 'SyncScreen'],
      [1, 'Button', 'View', 3],
      [1, 'Toast', 'Text', 9],
    ],
    code: [
      'const rows = makeRows(§rows§); // ~140 bytes per row',
      'await Db.saveRows(rows);',
      "showToast('Saved');",
    ],
  },
]

/** Startup module names (prototype `static POOL`). */
export const MODULE_POOL = [
  'Storage',
  'Analytics',
  'Camera',
  'Maps',
  'Bluetooth',
  'Payments',
  'Contacts',
  'Location',
  'Biometrics',
  'Haptics',
  'Calendar',
  'Notifications',
  'Share',
  'Clipboard',
  'Audio',
  'Video',
  'NFC',
  'Sensors',
  'Keychain',
  'WebView',
] as const

export const PRESET_IDS: readonly PresetId[] = PRESETS.map((p) => p.id)

export const isPresetId = (v: unknown): v is PresetId => typeof v === 'string' && (PRESET_IDS as readonly string[]).includes(v)

export function presetById(id: PresetId): Preset {
  return PRESETS.find((p) => p.id === id) ?? PRESETS[0]
}
